services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core-network
    command: sleep infinity

networks:
  core-network:
    external: true
